# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/edges.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12shared/edges.proto\x12\x05\x65\x64ges\"\x1c\n\x0c\x45\x64gesMessage\x12\x0c\n\x04urls\x18\x01 \x03(\tb\x06proto3')



_EDGESMESSAGE = DESCRIPTOR.message_types_by_name['EdgesMessage']
EdgesMessage = _reflection.GeneratedProtocolMessageType('EdgesMessage', (_message.Message,), {
  'DESCRIPTOR' : _EDGESMESSAGE,
  '__module__' : 'shared.edges_pb2'
  # @@protoc_insertion_point(class_scope:edges.EdgesMessage)
  })
_sym_db.RegisterMessage(EdgesMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EDGESMESSAGE._serialized_start=29
  _EDGESMESSAGE._serialized_end=57
# @@protoc_insertion_point(module_scope)
