[package]
name = "selector-service"
version = "0.1.0"
edition = "2021"

[dependencies]
lapin = "2.3.4"
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tokio-executor-trait = "2.1.1"
tokio-reactor-trait = "1.1.0"
anyhow = "1.0.86"
redis = { version = "0.25.4", features = ["aio", "tokio-comp"] }
futures = "0.3.30"
uuid = { version = "1.8.0", features = ["fast-rng", "v4"] }
serde = { version = "1.0.203", features = ["derive"] }
utils = { path = "../utils", features = ["redis"]}
rand = "0.8.5"
